name: kimmyszeto
favicon: null
layout_spectrum: 0.06110282591544092
typography_spectrum: 0.8106590264942497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.12907048547640443
  saturation: 0.95912626828067
  rhythmicContrast: 0.75
purpose: []
