name: kimmyszeto
favicon: null
layout_spectrum: 0.49971
typography_spectrum: 0.4889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#175399'
    - '#78a489'
    - '#047b4d'
    - '#588426'
    - '#245d2d'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
